export const environment = {
  production: true,
  backendHost: 'https://api.fostersource.org',
  useRealAnnouncementService: true,
  useRealAccountService: true,
  useRealProfileService: true,
  useRealAddressService: true,
  useRealAvailabilityService: true,
  useRealBlacklistService: true,
  useRealPhoneNumberService: true,
  useRealProfilePhotosService: true,
  useRealAuthService: true,
  useRealImageService: true,
  useRealBugService: true,
  imageBucket: 'respite-source-images-dev',
  bucketRegion: 'us-west-1',
};
